# Generated by Django 5.0.6 on 2024-05-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_vault', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='snippet_vau_title_47df50_idx'),
        ),
    ]
